### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by stevenmchoi** [stevenmchoi/grease_munchy#1]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by wongshington** [comment]
- [x] demo login button doesn't work yet
- [x] should clear errors between session forms
- [x] errors should have a little space between the session form and where they render

**Comment by wongshington** [comment]
-for future MVP's don't worry too much about adding in extra animations and what not, the main focus for right now is functionality and completion
it all looks good though!

**Comment by stevenmchoi** [comment]
Got it. Thanks for reviewing in place of Isak! Oddly enough, I was about to do something more complicated to try to erase the errors from the props, but I realized that I could use the animation to simply hide it when mounting each time. Kinda feels like I'm cheating, but it works :)
